# Generated by Django 4.1.4 on 2022-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAIL', 'Mail'), ('JESLASTIC', 'Jelastic'), ('SWISSBACKUP', 'Swissbackup'), ('NEWSLETTER', 'Newsletter'), ('BILLETERIE', 'Billeterie'), ('PUBLICCLOUD', 'Publiccloud'), ('KDRIVE', 'Kdrive'), ('KCHAT', 'Kchat'), ('CALENDRIER', 'Calendrier'), ('VOD/AOD', 'Vod/Aod'), ('SERVERCLOUD', 'Servercloud'), ('DOMAINES', 'Domaines'), ('SSL', 'Ssl')], default='MAIL', max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
